## 3. Fit the model / algorithm on our data and use it to make prediction

### 3.1 Fitting the model to the data
* `X` = features, feature variables, data
* `Y` = labels, targets, target variables

In [2]:
import numpy as np
import pandas as pd

In [3]:
heart_desease = pd.read_csv("./csv/heart-disease.csv")

In [6]:
# Import the RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

# Setup random seed
np.random.seed(42)

# Mkae the data
x = heart_desease.drop("target", axis=1)
y = heart_desease['target']

X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=.2)

In [7]:
clf = RandomForestClassifier()
clf.fit(X_train, Y_train)
clf.score(X_test, Y_test)

0.8524590163934426

### 3.2 Make predictions using a machine learnign model

2 way to make predictions:
1. Predict()
1. predict_pb()

In [8]:
clf.predict(np.array([1,2,7,46,75])) # this doesn't work

ValueError: Expected 2D array, got 1D array instead:
array=[ 1.  2.  7. 46. 75.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [9]:
clf.predict(X_test)

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

In [10]:
np.array(Y_test)

array([0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

In [11]:
# Compare prediction to truth labels to evaluate the model
y_preds = clf.predict(X_test)
np.mean(y_preds == Y_test)

0.8524590163934426

In [12]:
clf.score(X_test, Y_test)

0.8524590163934426

In [13]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test, y_preds)

0.8524590163934426

Make predictions with `predict_pa()`


In [14]:
# predict_proba() to predict probability estimate
clf.predict_proba(X_test[:5])

array([[0.89, 0.11],
       [0.49, 0.51],
       [0.43, 0.57],
       [0.84, 0.16],
       [0.18, 0.82]])

In [15]:
clf.predict(X_test[:5])

array([0, 1, 1, 0, 1])

In [16]:
from sklearn.datasets import load_boston
boston = load_boston()
boston_df = pd.DataFrame(boston['data'], columns=boston['feature_names'])
boston_df["target"] = pd.Series(boston['target'])
boston_df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  target  
0     15.3  396.90   4.98    24.0  
1     17.8  396.90   9.14    21.6  
2     17.8  392.83   4.03    34.7  
3     18.7  394.63   2.94    33.4  
4     18.7  396.90   5.33    36.2

In [17]:
from sklearn.ensemble import RandomForestRegressor
np.random.seed(42)
x = boston_df.drop('target', axis=1)
y = boston_df['target']

In [19]:
X_train, X_test, Y_train, Y_test = train_test_split(x,y, test_size=.2)

rf = RandomForestRegressor()
rf.fit(X_train, Y_train)
rf.score(X_test, Y_test)

0.8951591526849659

In [27]:
y_preds = rf.predict(X_test)
y_preds[:10]

array([30.562, 46.948, 30.38 , 21.823, 14.825, 17.862, 12.583, 33.83 ,
       15.253, 20.498])

In [28]:
Y_test[:10]

197    30.3
280    45.4
284    32.2
318    23.1
127    16.2
122    20.5
423    13.4
231    31.7
458    14.9
15     19.9
Name: target, dtype: float64

In [29]:
# Compare the prediction to the truth
from sklearn.metrics import mean_absolute_error
mean_absolute_error(Y_test, y_preds)

2.0712941176470583